apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-12-12T06:24:22Z"
  generation: 1
  labels:
    app: web-003
  name: web-003
  namespace: default
  resourceVersion: "461665"
  uid: a23f45ad-b8cb-4d43-8459-92d8c0b8077d
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web-003
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-003
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
