apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: audit-web-app
  name: audit-web-app-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort : 30002
  selector:
    run: audit-web-app
  type: NodePort